#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";

const args = process.argv.slice(2);

const skipServer = args.includes("-n") || args.includes("--no-server");
const js = args.includes("-js" || args.includes("--javascript"));

const positionalArgs = args.filter((arg) => !arg.startsWith("-"));

const command = positionalArgs[0];
const routePath = positionalArgs[1];
const routeName = positionalArgs[2];

console.log(command);

if (command === "route") {
  if (!routePath) {
    console.error("❌ Error: Missing route path.");
    console.log("💡 Usage: npx svelte-maker route <path> [routeName] [-n]");
    process.exit(1);
  }

  const targetDir = path.resolve(process.cwd(), "src/routes", routePath);

  try {
    fs.mkdirSync(targetDir, { recursive: true });

    const pageSvelteContent = `<script${js ? "" : ' lang="ts"'}>\n    let { data } = $props();\n</script>\n\n<h1>Generated by svelte maker!</h1>\n`;
    fs.writeFileSync(path.join(targetDir, "+page.svelte"), pageSvelteContent);

    if (routeName) {
      const pageTsContent = `export const config = {\n    name: '${routeName}'\n};\n`;
      fs.writeFileSync(
        path.join(targetDir, `+page.${js ? "js" : "ts"}`),
        pageTsContent,
      );
    }

    if (!skipServer) {
      let pageServerContent = "";

      if (js) {
        pageServerContent = `export const load = async () => {\n    return {};\n};\n`;
      } else {
        pageServerContent = `import type { PageServerLoad } from './$types';\n\nexport const load: PageServerLoad = async () => {\n    return {};\n};\n`;
      }
      fs.writeFileSync(
        path.join(targetDir, `+page.server.${js ? "js" : "ts"}`),
        pageServerContent,
      );
    }

    console.log(`✅ Success! Route created at src/routes/${routePath}`);
    console.log(`   📄 +page.svelte`);
    if (routeName)
      console.log(`   📄 +page.${js ? "js" : "ts"} (Config: ${routeName})`);
    if (!skipServer) console.log(`   📄 +page.server.${js ? "js" : "ts"}`);
  } catch (error) {
    console.error("❌ Failed to create route:", error.message);
    process.exit(1);
  }
} else if (command === "init") {
  const pkgPath = path.resolve(process.cwd(), "package.json");

  try {
    if (!fs.existsSync(pkgPath)) {
      console.error("❌ Error: No package.json found in this directory.");
      process.exit(1);
    }

    const pkgData = fs.readFileSync(pkgPath, "utf-8");
    const pkg = JSON.parse(pkgData);

    pkg.scripts = pkg.scripts || {};

    pkg.scripts["make:route"] = "svelte-maker route";

    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");

    console.log("✅ Success! Added 'make:route' alias to your package.json.");
    console.log("💡 You can now run: npm run make:route <path>");
  } catch (error) {
    console.error("❌ Failed to update package.json:", error.message);
    process.exit(1);
  }
} else {
  console.log("Unknown command. Available commands: route");
}
